spring:
  mvc:
    hiddenmethod:
      filter:
        enabled: true
  liquibase:
        contexts: prod
  datasource:
    url: jdbc:mysql://localhost:3306/FilmWave?createDatabaseIfNotExist=true
    username: root
    password: bazahaslo
  web:
    resources:
      static-locations: classpath:/static/,file:/Users/lukas/uploads
app:
  storage:
    location: uploads
  jpa:
      properties:
        hibernate:
          dialect: org.hibernate.dialect.MySQLDialect