spring:
  mvc:
    hiddenmethod:
      filter:
        enabled: true
  h2:
    console:
      enabled: false
  datasource:
    url: jdbc:mysql://localhost:3306/movieHub?createDatabaseIfNotExist=true
    username: root
    password: bazahaslo
  liquibase:
    contexts: prod
  web:
    resources:
      static-locations: classpath:/static/,file:/Users/lukas/uploads
app:
  storage:
    location: /Users/lukas/uploads